import assert from "node:assert/strict"; import {newBtcResearchFieldIdentity,hashBtcResearchFieldSecret,normalizeBtcResearchFieldId,normalizeBtcResearchFieldSecret,buildBtcResearchContinuityDigest,buildBtcResearchFieldModelContext,hashBtcResearchFieldTurnResult,isBtcResearchFieldActive,BTC_RESEARCH_FIELD_MAX_TURNS} from "../lib/btc-research-field-v1"; import {resolveBtcCleanChatModelTransport} from "../lib/btc-clean-chat-model-runtime";
const id=newBtcResearchFieldIdentity(); assert.equal(normalizeBtcResearchFieldId(id.fieldId),id.fieldId); assert.equal(normalizeBtcResearchFieldSecret(id.secret),id.secret); assert.equal(hashBtcResearchFieldSecret(id.secret),id.secretHash); assert.notEqual(id.secret,id.secretHash);
const field:any={fieldId:id.fieldId,secretHash:id.secretHash,status:'ACTIVE',locale:'en',title:'BTC liquidity',primaryQuestion:'What changed?',timeHorizon:'2026',evidencePreferences:['polymarket'],watchConditions:[],exactPolymarketContracts:[],serviceStart:new Date(Date.now()-1000).toISOString(),serviceEnd:new Date(Date.now()+100000).toISOString(),completedTurns:0,activeTurnId:null,activeTurnClaimedAt:null}; assert.equal(isBtcResearchFieldActive(field),true); field.completedTurns=BTC_RESEARCH_FIELD_MAX_TURNS; assert.equal(isBtcResearchFieldActive(field),false); field.completedTurns=0;
const result:any={ok:true,topic:'Bitcoin',answer:'Current evidence is fresh.',as_of:new Date().toISOString(),sources:[],evidence:{accepted_snapshot:'USED'},boundary:{no_trading_signal:true},usage:{provider:'DIRECT_OPENAI_API',model:'gpt-5.6-sol',input_tokens:1,output_tokens:1,web_search_calls:0}}; const turnHash=hashBtcResearchFieldTurnResult('What changed?',result); assert.match(turnHash,/^[a-f0-9]{64}$/); assert.notEqual(turnHash,hashBtcResearchFieldTurnResult('What changed?',{...result,answer:'tampered'})); const digest=buildBtcResearchContinuityDigest({question:'What changed?',result}); assert.match(digest,/Current evidence/); const cp:any={continuityDigest:digest}; const ctx=buildBtcResearchFieldModelContext(field,{...cp,role:'BASELINE'},cp); assert.equal(ctx.baseline_digest,digest); assert.match(ctx.memory_boundary,/never overrides current evidence/i); console.log('PASS_BTC_RESEARCH_FIELD_V1_ACCEPTANCE');

const directTransport=resolveBtcCleanChatModelTransport({}); assert.equal(directTransport.endpoint,"https://api.openai.com/v1/responses"); assert.equal(directTransport.model,"gpt-5.6-sol"); assert.equal(directTransport.authEnv,"OPENAI_API_KEY");
const previewTransport=resolveBtcCleanChatModelTransport({VERCEL_ENV:"preview",BTC_RESEARCH_FIELD_MODE:"preview_v1",BTC_RESEARCH_FIELD_PREVIEW_RESPONSES_URL:"https://preview-provider.example/v1/responses",BTC_RESEARCH_FIELD_PREVIEW_MODEL_ID:"openai/gpt-5.6-sol",BTC_RESEARCH_FIELD_PREVIEW_BEARER:"temporary"}); assert.equal(previewTransport.endpoint,"https://preview-provider.example/v1/responses"); assert.equal(previewTransport.model,"openai/gpt-5.6-sol"); assert.equal(previewTransport.authEnv,"BTC_RESEARCH_FIELD_PREVIEW_BEARER");
assert.throws(()=>resolveBtcCleanChatModelTransport({VERCEL_ENV:"preview",BTC_RESEARCH_FIELD_MODE:"preview_v1"}),/PREVIEW_PROVIDER_UNAVAILABLE/);
const prodTransport=resolveBtcCleanChatModelTransport({VERCEL_ENV:"production",BTC_RESEARCH_FIELD_MODE:"preview_v1",BTC_RESEARCH_FIELD_PREVIEW_RESPONSES_URL:"https://preview-provider.example/v1/responses",BTC_RESEARCH_FIELD_PREVIEW_MODEL_ID:"other",BTC_RESEARCH_FIELD_PREVIEW_BEARER:"temporary"}); assert.equal(prodTransport.endpoint,"https://api.openai.com/v1/responses");
