import Head from "next/head";
import Link from "next/link";
import type { GetServerSideProps } from "next";
import { BTC_SOURCE_URLS, loadBtcStaticSource } from "../../lib/btc-public-static-source";
import { composeBtcPublicSnapshot } from "../../lib/btc-public-snapshot-composer";
import { renderBtcNarrativeRead } from "../../lib/btc-narrative-template-catalog";
import type { BtcNarrativeSectionFactPayload } from "../../lib/btc-deterministic-narrative-router";
import { loadBtcMarketEnvelope, type BtcMarketEnvelope, type BtcMarketEnvelopeFailure, type BtcMetricDelta } from "../../lib/btc-market-envelope";
import { formatBtcDominanceBandLabel, formatBtcFocusAxisLabel, formatBtcFreshnessLabel, formatBtcMarketContextLabel, formatBtcObservationDate, formatBtcProofSourceLabel, formatBtcProofStatusLabel, formatBtcQuestionLensLabel, formatBtcSafetyOverlayLabel, formatBtcTemporalStateLabel, formatBtcUtcTimestamp, formatBtcWatchConditionForDisplay, getBtcReadRolePresentation } from "../../lib/btc-public-display-labels";
import type { BtcFailureCode, BtcPublicSnapshot } from "../../lib/btc-public-output-contract";

type Failure = { code: BtcFailureCode; message: string; last_verified_at_utc: string | null };
type EnvelopeFailure = { code: BtcMarketEnvelopeFailure["code"]; message: string; last_verified_at_utc: string | null };
type Props = { result: BtcPublicSnapshot | null; failure: Failure | null; envelope: BtcMarketEnvelope | null; envelopeFailure: EnvelopeFailure | null; initialQuestion: string; initialDate: string };
const first = (v: string | string[] | undefined) => Array.isArray(v) ? v[0] ?? "" : v ?? "";

export const getServerSideProps: GetServerSideProps<Props> = async ({ query }) => {
  const initialQuestion=first(query.q), initialDate=first(query.d);
  const empty:Props={result:null,failure:null,envelope:null,envelopeFailure:null,initialQuestion:"",initialDate};
  if(!initialQuestion)return{props:empty};
  const source=await loadBtcStaticSource();
  if(source.ok===false)return{props:{...empty,initialQuestion,failure:{code:source.code,message:source.message,last_verified_at_utc:source.last_verified_at_utc??null}}};
  const composed=await composeBtcPublicSnapshot(source,{question:initialQuestion,date:initialDate||undefined});
  if(composed.ok===false)return{props:{...empty,initialQuestion,failure:{code:composed.code,message:composed.message,last_verified_at_utc:null}}};
  const market=await loadBtcMarketEnvelope(initialQuestion,{temporal:{state:composed.value.temporal_context.state,label:composed.value.temporal_context.label,harmonic_tension:composed.value.aspect_pressure.harmonic_tension}});
  return{props:{result:composed.value,failure:null,envelope:market.ok===true?market.value:null,envelopeFailure:market.ok===true?null:{code:market.code,message:market.message,last_verified_at_utc:market.last_verified_at_utc??null},initialQuestion,initialDate}};
};

const compact=(value:number,decimals:number)=>value.toFixed(decimals).replace(/\.0+$|(?<=\.[0-9]*?)0+$/g,"").replace(/\.$/,"");
const money=(value:number,signed=false)=>{
  const absolute=Math.abs(value);
  const divisor=absolute>=1e12?1e12:absolute>=1e9?1e9:absolute>=1e6?1e6:absolute>=1e3?1e3:1;
  const suffix=divisor===1e12?"T":divisor===1e9?"B":divisor===1e6?"M":divisor===1e3?"K":"";
  const scaled=absolute/divisor;
  const digits=suffix?(scaled>=100?0:2):2;
  const sign=value<0?"−":signed&&value>0?"+":"";
  return `${sign}$${compact(scaled,digits)}${suffix}`;
};
const pct=(value:number,decimals=2,signed=true)=>`${value<0?"−":signed&&value>0?"+":""}${compact(Math.abs(value),decimals)}%`;
const plain=(value:string)=>value.replace(/_/g," ").replace(/\b\w/g,char=>char.toUpperCase());
const stateLabel=(value:string)=>({CONFIRMATION:"Confirmation",DIVERGENCE:"Mixed signals",INSUFFICIENT_EVIDENCE:"Evidence limited",UP:"Strengthening",DOWN:"Weakening",UNCHANGED:"Stable",BOUNDED:"Mixed",UNAVAILABLE:"Unavailable"}[value]??plain(value));
const roleLabel=(value:string)=>value==="primary"?"Primary for this question":value==="unavailable"?"Not available":"Supporting context";
const memoryLabel=(id:string)=>({btc_gravity_pct:"BTC dominance",stablecoin_share_pct:"Stablecoin share",alt_breadth_24h_pct:"Alt breadth · 24h",alt_breadth_7d_pct:"Alt breadth · 7d",market_field_score:"Market Field Score",regime_label:"Regime",defi_tvl_usd:"DeFi TVL",liquidity_context_state:"Liquidity context"}[id]??plain(id));
const memoryValue=(m:BtcMetricDelta,value:string)=>{const numeric=Number(value);if(m.type!=="NUMERIC"||!Number.isFinite(numeric))return plain(value);if(m.unit==="usd")return money(numeric);if(m.unit==="percent")return `${compact(numeric,m.metric_id.includes("breadth")?1:2)}%`;if(m.unit==="score_0_100")return compact(numeric,1);return compact(numeric,2)};
const memoryDelta=(m:BtcMetricDelta)=>{if(m.type!=="NUMERIC")return m.transition==="UNCHANGED"?"No change":plain(m.transition??m.direction);const numeric=Number(m.display_delta);if(!Number.isFinite(numeric))return stateLabel(m.direction);if(m.unit==="usd")return money(numeric,true);const sign=numeric<0?"−":numeric>0?"+":"";const value=compact(Math.abs(numeric),m.metric_id.includes("breadth")||m.unit==="score_0_100"?1:2);return m.unit==="percent"?`${sign}${value} pp`:`${sign}${value} pts`};
const examples=["What changed in the BTC field and why does it matter?","What does BTC dominance mean for the wider market?","What do liquidity, breadth, and pressure show now?","How does the selected date change the observation context?","Which BTC conditions should I watch?"] as const;
const titles:Record<BtcNarrativeSectionFactPayload["section_id"],string>={what_changed:"ROLLING MARKET CONTEXT",why_it_matters:"WHY IT MATTERS",current_structure:"CURRENT STRUCTURE",dominant_pressures:"DOMINANT PRESSURES",relative_market_field:"RELATIVE MARKET FIELD",temporal_context:"TEMPORAL CONTEXT"};
function facts(p:BtcNarrativeSectionFactPayload){switch(p.section_id){case"what_changed":return`BTC ${money(p.price_usd)} · 24h ${pct(p.change_24h_pct)} · 7d ${pct(p.change_7d_pct)} · 30d ${pct(p.change_30d_pct)} · total-cap 24h ${pct(p.market_cap_change_24h_pct)}.`;case"why_it_matters":return`Dominance ${p.dominance_pct.toFixed(2)}% · ${formatBtcDominanceBandLabel(p.dominance_band)} · rank #${p.market_cap_rank} · ${formatBtcMarketContextLabel(p.market_context_label)}.`;case"current_structure":return`${p.regime_label} · field ${p.field_score.toFixed(1)} · ${p.direction_bias} · ${p.liquidity_state}.`;case"dominant_pressures":return`${p.pressure_label} · ${formatBtcTemporalStateLabel(p.temporal_state)} · ${p.harmonic_tension===null?"numeric pressure unavailable":`tension ${p.harmonic_tension.toFixed(4)}`} · stablecoin share ${p.stablecoin_share_pct.toFixed(2)}%.`;case"relative_market_field":return`BTC dominance ${p.dominance_pct.toFixed(2)}% · alt breadth ${p.alt_breadth_24h_pct.toFixed(1)}% · stablecoin share ${p.stablecoin_share_pct.toFixed(2)}%.`;case"temporal_context":return`${formatBtcTemporalStateLabel(p.temporal_state)} · observation ${formatBtcObservationDate(p.observation_date)} · market source ${formatBtcUtcTimestamp(p.source_generated_at_utc)}.`;}}

function ExecutiveRead({e}:{e:BtcMarketEnvelope}){const changed=e.synthesis.what_changed.slice(0,2);const confirms=e.synthesis.confirming_modules.slice(0,2);const weakens=e.synthesis.contradicting_or_weakening_modules.slice(0,2);return <section className="executiveRead" aria-labelledby="executive-read-title">
  <header><div><p className="eyebrow">Executive Cosmographer Read</p><h2 id="executive-read-title">{stateLabel(e.synthesis.state)}</h2></div><b className={`state ${e.synthesis.state.toLowerCase().replace("_","-")}`}>{stateLabel(e.synthesis.state)}</b></header>
  <div className="executiveGrid"><article><span>What changed</span><p>{changed[0]??"No comparable transition is asserted."}</p></article><article><span>What confirms it</span><p>{confirms[0]??"No multi-module confirmation is asserted."}</p></article><article><span>What weakens it</span><p>{weakens[0]??"No contradiction is asserted."}</p></article><article><span>Watch next</span><p>{e.synthesis.watch_next[0]??"Wait for the next accepted snapshot."}</p></article></div>
  <p className="executiveBoundary"><b>Uncertainty boundary.</b> {e.synthesis.uncertainty[0]??"The read remains bounded to accepted static evidence."}</p>
</section>}

function ModuleCard({node,primary=false}:{node:BtcMarketEnvelope["phi_geometry"]["nodes"][number];primary?:boolean}){return <article className={`moduleNode ${primary?"modulePrimary":"moduleSupport"} ${node.role==="unavailable"?"moduleUnavailable":""}`} data-role={node.role}>
  <header><i>{node.index}</i><em>{roleLabel(node.role)}</em></header><h3>{node.label}</h3><b className="direction">{stateLabel(node.state)}</b><p>{node.evidence[0]??"Evidence is not available for this module."}</p>
</article>}

function PhiField({e}:{e:BtcMarketEnvelope}){const primary=e.phi_geometry.nodes.filter(node=>node.role==="primary");const support=e.phi_geometry.nodes.filter(node=>node.role!=="primary");return <section className="phiSection" aria-labelledby="phi-field-title">
  <header className="sectionHeading"><div><p className="eyebrow">Unified semantic field</p><h2 id="phi-field-title">Five-module Φ-field</h2></div><p>Two modules lead this question. Three modules remain supporting or unavailable.</p></header>
  <div className="phiComposition">
    <div className="primaryField"><ModuleCard node={primary[0]} primary/><div className="btcCore"><span>BTC</span><b>Central gravity</b><small>{plain(e.question_class)}</small><p>{e.memory.transition_interpretation}</p></div><ModuleCard node={primary[1]} primary/></div>
    <div className="supportField">{support.map(node=><ModuleCard key={node.id} node={node}/>)}</div>
  </div>
  <p className="phiCaption">61.803% primary attention · 38.197% supporting context · Φ {e.phi_geometry.phi_constant}</p>
</section>}

function MemoryAndSynthesis({e}:{e:BtcMarketEnvelope}){return <section className="memorySynthesis" aria-labelledby="memory-title">
  <div><p className="eyebrow">Accepted Change Memory</p><h2 id="memory-title">Previous → current</h2><p>{e.memory.comparable_metric_count} comparable metrics · {e.memory.unavailable_metrics.length} unavailable</p><div className="memoryStrip">{e.memory.metrics.map(metric=><article key={metric.metric_id}><span>{memoryLabel(metric.metric_id)}</span><b>{memoryDelta(metric)}</b><small>{memoryValue(metric,metric.previous_value)} → {memoryValue(metric,metric.current_value)}</small></article>)}</div></div>
  <aside><p className="eyebrow">Confirmation / divergence</p><h2>{stateLabel(e.synthesis.state)}</h2><p>{e.synthesis.why_this_matters}</p><h3>Watch next</h3><ul>{e.synthesis.watch_next.slice(0,3).map(item=><li key={item}>{item}</li>)}</ul></aside>
</section>}

function Envelope({e,result}:{e:BtcMarketEnvelope;result:BtcPublicSnapshot}){return <>
  <section className="currentMetrics" aria-labelledby="current-metrics-title"><header className="sectionHeading"><div><p className="eyebrow">Current verified metrics</p><h2 id="current-metrics-title">BTC and market envelope</h2></div><p>{formatBtcUtcTimestamp(e.current.source_generated_at_utc)}</p></header><div className="metricGrid">
    <article><span>BTC</span><strong>{money(e.current.price_usd)}</strong><small>24h {pct(e.current.change_24h_pct)} · 7d {pct(e.current.change_7d_pct)} · 30d {pct(e.current.change_30d_pct)}</small></article>
    <article><span>Dominance</span><strong>{pct(e.current.btc_dominance_pct,2,false)}</strong><small>Total cap {money(e.current.total_market_cap_usd)}</small></article>
    <article><span>Market Field</span><strong>{compact(e.current.market_field_score,1)}</strong><small>{e.current.regime} · {plain(e.current.direction_bias)}</small></article>
    <article><span>Liquidity</span><strong>{money(e.current.defi_tvl_usd)}</strong><small>DEX 24h {money(e.current.dex_volume_24h_usd)}</small></article>
    <article><span>Participation</span><strong>{pct(e.current.alt_breadth_24h_pct,1,false)}</strong><small>7d {pct(e.current.alt_breadth_7d_pct,1,false)} · ETH {pct(e.current.eth_rotation_anchor_pct,2,false)}</small></article>
    <article><span>Stablecoins</span><strong>{pct(e.current.stablecoin_share_pct,2,false)}</strong><small>{money(e.current.stablecoin_cap_usd)}</small></article>
  </div></section>
  <ExecutiveRead e={e}/><PhiField e={e}/><MemoryAndSynthesis e={e}/>
  <section className="evidenceStack" aria-label="Detailed evidence">
    <details><summary>Detailed module evidence</summary><div className="moduleDetails">{result.cosmographer_read.sections.map(sec=>{const role=getBtcReadRolePresentation(sec.role);return <article key={sec.section_id}><header><span>{String(sec.order).padStart(2,"0")}</span><b>{titles[sec.section_id]}</b><em>{role.badge==="PRIMARY READ"?"Primary":"Supporting"}</em></header><p><strong>Facts.</strong> {facts(sec.fact_payload)}</p><p><strong>Cosmographer read.</strong> {renderBtcNarrativeRead(sec.read_template_id,sec.fact_payload)}</p></article>})}</div><div className="detailColumns"><section><h3>Watch conditions</h3><ol>{result.watch_conditions.map(item=><li key={item}>{formatBtcWatchConditionForDisplay(item)}</li>)}</ol></section><section><h3>Uncertainty</h3><p>{result.uncertainty.freshness}</p><p>{result.uncertainty.question_limit}</p><p>{result.uncertainty.temporal_limit}</p><p>{result.uncertainty.source_limit}</p></section></div></details>
    <details><summary>All eight memory metrics and exact accepted values</summary><div className="memoryTable">{e.memory.metrics.map(metric=><article key={metric.metric_id}><div><b>{memoryLabel(metric.metric_id)}</b><span>{memoryDelta(metric)}</span></div><p>{memoryValue(metric,metric.previous_value)} → {memoryValue(metric,metric.current_value)}</p><details><summary>Exact values and methodology</summary><code>previous={metric.previous_value}</code><code>current={metric.current_value}</code><code>methodology={metric.methodology_id}</code><code>sources={metric.proof_sources.join(",")}</code></details></article>)}</div></details>
    <details><summary>Verified history</summary>{e.verified_history.available?<><p>{e.verified_history.observation_window}</p><div className="historyGrid">{e.verified_history.checkpoints.map(checkpoint=><article key={checkpoint.snapshot_id}><span>{plain(checkpoint.role)}</span><h3>{formatBtcUtcTimestamp(checkpoint.accepted_at_utc)}</h3><p>BTC {money(checkpoint.btc_price_usd)} · dominance {pct(checkpoint.btc_dominance_pct,2,false)}</p><p>Breadth {pct(checkpoint.alt_breadth_24h_pct,1,false)} / {pct(checkpoint.alt_breadth_7d_pct,1,false)} · stable share {pct(checkpoint.stablecoin_share_pct,2,false)}</p><p>Field {compact(checkpoint.market_field_score,1)} · {checkpoint.regime}</p><code>{checkpoint.commit_sha}</code></article>)}</div><p className="methodNote">{e.verified_history.methodology_repair_disclosure}</p></>:<p>Historical comparison is suppressed because an immutable accepted checkpoint could not be verified.</p>}</details>
    <details><summary>Source proof, hashes and public boundaries</summary><p><a href={e.source_proof.registry_url}>Snapshot Registry</a> · <a href={e.source_proof.delta_url}>Snapshot Delta</a> · <a href={e.source_proof.previous_snapshot_url}>Previous immutable snapshot</a></p><div className="proofSources">{result.source_proof.sources.map(source=><article key={source.label}><b>{formatBtcProofSourceLabel(source.label)}</b><span>{formatBtcProofStatusLabel(source.status)} · {formatBtcUtcTimestamp(source.fetched_at_utc)}</span><a href={source.url}>Open source</a><code>{source.sha256}</code></article>)}</div><div className="hashList"><code>current snapshot · {e.source_proof.current_snapshot_sha256}</code><code>previous snapshot · {e.source_proof.previous_snapshot_sha256}</code><code>current proof · {e.source_proof.current_proof_sha256}</code><code>previous proof · {e.source_proof.previous_proof_sha256}</code><code>current bindings · {e.source_proof.current_bindings_sha256}</code><code>previous bindings · {e.source_proof.previous_bindings_sha256}</code></div><section className="closingBoundary"><h3>Public boundary</h3><p>Read only · static accepted evidence · no live adapter claim · no trading signal · no forecast · no price target · no investment recommendation · no personal-memory claim · ORION protected.</p><p><b>Inactive:</b> {e.inactive_modules.join(" · ")}</p></section></details>
  </section>
</>}

export default function Page({result,failure,envelope,envelopeFailure,initialQuestion,initialDate}:Props){const inputFailure=failure?.code==="invalid_input",date=initialDate?`&d=${encodeURIComponent(initialDate)}`:"";return <><Head><title>BTC Field Read · Market Cosmographer</title><meta name="description" content="BTC-centric, whole-market-aware Cosmographer field using static accepted evidence and Snapshot Memory."/></Head><main>
  <section className="hero"><p className="eyebrow">Market Cosmographer · BTC corridor</p><h1>BTC Field Read</h1><p>BTC remains the gravity anchor. The wider market forms the analytical envelope.</p></section>
  <section className="questionPanel" aria-labelledby="btc-question-title"><header><div><p className="eyebrow">Question and observation</p><h2 id="btc-question-title">Ask one BTC field question</h2></div>{result&&<div className="observation"><span>Observation</span><b>{formatBtcObservationDate(result.temporal_context.observation_date)}</b></div>}</header><form method="get" action="/crypto-astro/btc"><label>Question<textarea name="q" minLength={8} maxLength={280} required defaultValue={initialQuestion} placeholder="What changed in the BTC field, why does it matter, and what conditions should I watch?"/></label><label>Observation date · UTC<input name="d" type="date" defaultValue={initialDate}/></label><button>Run BTC Field Read</button></form><details className="examples"><summary>Example questions</summary><div>{examples.map(question=><a key={question} href={`/crypto-astro/btc?q=${encodeURIComponent(question)}${date}`}>{question}</a>)}</div></details><p className="privacyNote">The date controls only the bounded temporal lane. Do not include wallet addresses, keys, account details, or identifying information.</p></section>
  {failure&&<section className="failure" role="alert"><p className="eyebrow">{inputFailure?"Question check":"Source-bound failure"}</p><h2>{inputFailure?"Adjust the question or date":"BTC Field Read unavailable"}</h2><p>{failure.message}</p>{failure.last_verified_at_utc&&<p>Last verified: {formatBtcUtcTimestamp(failure.last_verified_at_utc)}</p>}<details><summary>Technical details</summary><code>{failure.code}</code></details></section>}
  {result&&<section className="reading" aria-label="BTC Cosmographer reading"><header className="readingQuestion"><div><span>Question</span><h2>{result.question.normalized}</h2></div><div><span>Lens</span><b>{formatBtcQuestionLensLabel(result.question.lens)}</b><small>{formatBtcFocusAxisLabel(result.question.geometry.focus_axis)}</small></div></header>{result.question.safe_reframed&&<p className="reframe"><b>{formatBtcSafetyOverlayLabel(result.question.geometry.safety_overlay)}.</b> Direct trading guidance was removed.</p>}{envelope?<Envelope e={envelope} result={result}/>:<section className="failure"><p className="eyebrow">Market envelope fail-closed</p><h2>Whole-market envelope unavailable</h2><p>{envelopeFailure?.message??"The analytical envelope could not be verified."}</p><p>The bounded BTC reader remains available, while Change Memory and cross-module synthesis stay suppressed.</p><details><summary>Bounded reader evidence</summary>{result.cosmographer_read.sections.map(sec=><article key={sec.section_id}><h3>{titles[sec.section_id]}</h3><p>{facts(sec.fact_payload)}</p><p>{renderBtcNarrativeRead(sec.read_template_id,sec.fact_payload)}</p></article>)}</details></section>}</section>}
  <div className="closingField" aria-hidden="true"><span/></div>
</main><style jsx>{`
:global(*){box-sizing:border-box}:global(html){scroll-padding-bottom:calc(clamp(128px,12vh,168px) + env(safe-area-inset-bottom))}:global(html,body){margin:0;background:#050a12;color:#e8eef6;font-family:Inter,system-ui,sans-serif;overflow-x:hidden}:global(a){color:#b7d2ff}:global(code){overflow-wrap:anywhere}:global(:focus-visible){outline:2px solid #f0cb70;outline-offset:3px}
main{width:min(1280px,100%);margin:auto;padding:28px 18px 0;display:grid;gap:18px}.hero,.questionPanel,.failure,.reading{min-width:0;border:1px solid #ffffff20;border-radius:24px;background:linear-gradient(180deg,#ffffff0c,#ffffff05)}.hero{padding:clamp(24px,4vw,48px);background:radial-gradient(circle at 12% 0,#f0cb701b,transparent 38%),#ffffff06}.hero h1{margin:8px 0 4px;font-size:clamp(42px,7vw,78px);letter-spacing:-.06em}.hero p:last-child{max-width:720px;color:#aebccc;font-size:clamp(16px,2vw,20px)}
.eyebrow{margin:0;color:#f0cb70;font:800 11px/1.3 system-ui;letter-spacing:.15em;text-transform:uppercase}.questionPanel{padding:clamp(18px,3vw,28px)}.questionPanel>header{display:flex;justify-content:space-between;gap:18px;align-items:start}.questionPanel h2,.failure h2{margin:7px 0 14px;font-size:clamp(24px,3vw,36px)}.observation{display:grid;gap:3px;text-align:right}.observation span,.readingQuestion span{font-size:10px;color:#8193a8;letter-spacing:.12em;text-transform:uppercase}.observation b{color:#f0cb70}form{display:grid;grid-template-columns:minmax(0,2fr) minmax(210px,.65fr) auto;gap:12px;align-items:end}label{display:grid;gap:7px;color:#bdc9d8;font-size:13px}textarea,input{width:100%;border:1px solid #ffffff27;border-radius:14px;padding:12px;background:#07111d;color:#f0f5fa;font:inherit}textarea{min-height:76px;resize:vertical}button{border:1px solid #f0cb7077;border-radius:999px;padding:13px 18px;background:#f0cb7015;color:#f0cb70;font-weight:800;cursor:pointer}.examples{margin-top:14px}.examples summary{cursor:pointer;color:#d7b65c;font-weight:700}.examples>div{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.examples a{border:1px solid #9fc4ff2d;border-radius:999px;padding:8px 10px;text-decoration:none;font-size:12px}.privacyNote{margin-bottom:0;color:#8193a8;font-size:12px}.failure{padding:24px;border-color:#ff8c8c4d}.failure p,.failure li{color:#aebccc;line-height:1.6}
.reading{padding:clamp(18px,3vw,30px);display:grid;gap:18px;background:radial-gradient(circle at 0 0,#f3ce6b12,transparent 28%),#ffffff05}.readingQuestion{display:grid;grid-template-columns:minmax(0,1.618fr) minmax(220px,1fr);gap:18px;align-items:end;border-bottom:1px solid #ffffff18;padding-bottom:18px}.readingQuestion h2{margin:5px 0 0;font-size:clamp(24px,3vw,38px);letter-spacing:-.025em}.readingQuestion>div:last-child{display:grid;justify-items:end;gap:4px;text-align:right}.readingQuestion small{color:#8193a8}.reframe{margin:0;border-left:3px solid #f0cb70;padding:10px 14px;background:#f0cb700b;color:#aebccc}
.currentMetrics,.executiveRead,.phiSection,.memorySynthesis,.evidenceStack{min-width:0}.sectionHeading{display:flex;justify-content:space-between;gap:18px;align-items:end}.sectionHeading h2,.executiveRead h2,.memorySynthesis h2{margin:6px 0 0;font-size:clamp(22px,3vw,34px)}.sectionHeading>p{max-width:460px;margin:0;color:#8193a8;text-align:right}.metricGrid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:9px;margin-top:14px}.metricGrid article{min-width:0;display:grid;gap:4px;border:1px solid #ffffff17;border-radius:15px;padding:13px;background:#00000026}.metricGrid span{font-size:9px;color:#8193a8;letter-spacing:.1em;text-transform:uppercase}.metricGrid strong{font-size:clamp(17px,2vw,23px);color:#f0d17a}.metricGrid small{color:#91a3b8;line-height:1.4;overflow-wrap:anywhere}
.executiveRead{border:1px solid #f0cb7044;border-radius:20px;padding:clamp(17px,2.4vw,25px);background:linear-gradient(135deg,#f0cb7011,#72a8ff09)}.executiveRead>header{display:flex;justify-content:space-between;gap:16px;align-items:start}.state{display:inline-flex;border:1px solid #ffffff2b;border-radius:999px;padding:8px 11px;font-size:10px;letter-spacing:.08em;white-space:nowrap}.confirmation{color:#98dfb2}.divergence{color:#f0cb70}.insufficient-evidence{color:#e5abab}.executiveGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:16px}.executiveGrid article{border-top:1px solid #ffffff20;padding-top:10px}.executiveGrid span{font-size:9px;color:#d6b95f;letter-spacing:.1em;text-transform:uppercase}.executiveGrid p{margin:6px 0 0;color:#c1ccd9;line-height:1.48}.executiveBoundary{margin:16px 0 0;color:#8fa1b5;font-size:12px}
.phiSection{border-top:1px solid #ffffff17;padding-top:18px}.phiComposition{display:grid;grid-template-columns:minmax(0,1.61803398875fr) minmax(320px,1fr);gap:12px;margin-top:14px}.primaryField{min-height:390px;display:grid;grid-template-columns:minmax(0,1fr) minmax(148px,.72fr) minmax(0,1fr);gap:10px;align-items:center;border:1px solid #f0cb7040;border-radius:22px;padding:14px;background:radial-gradient(circle at 50% 50%,#f0cb7018,transparent 32%),#03090f}.btcCore{align-self:center;aspect-ratio:1;border:1px solid #f0cb7080;border-radius:50%;display:grid;place-content:center;text-align:center;padding:15px;background:radial-gradient(circle,#f0cb7026,transparent 68%);box-shadow:0 0 48px #f0cb7010}.btcCore>span{font-size:clamp(46px,5vw,72px);font-weight:900;color:#f0cb70;letter-spacing:-.06em}.btcCore>b{font-size:10px;letter-spacing:.14em;text-transform:uppercase}.btcCore small{color:#8193a8}.btcCore p{margin:10px 0 0;color:#aebccc;font-size:10px;line-height:1.35}.moduleNode{min-width:0;border:1px solid #ffffff1b;border-radius:17px;padding:13px;background:#07101a;overflow:hidden}.moduleNode header{display:flex;justify-content:space-between;gap:8px}.moduleNode i,.moduleNode em{font-size:9px;color:#8193a8}.moduleNode h3{margin:12px 0 6px;color:#e3c76d;font-size:12px;letter-spacing:.06em}.moduleNode .direction{font-size:11px}.moduleNode p{margin:8px 0 0;color:#91a3b8;font-size:11px;line-height:1.42}.modulePrimary{border-color:#f0cb708a;background:linear-gradient(145deg,#f0cb701c,#08111b);box-shadow:inset 0 0 0 1px #f0cb7026}.modulePrimary h3{font-size:14px;color:#f4d77c}.moduleUnavailable{opacity:.58;border-style:dashed}.supportField{display:grid;grid-template-columns:1fr 1fr;gap:10px}.supportField .moduleNode:last-child{grid-column:1/-1}.phiCaption{margin:10px 0 0;text-align:right;color:#718297;font-size:10px}
.memorySynthesis{display:grid;grid-template-columns:minmax(0,1.618fr) minmax(300px,1fr);gap:12px}.memorySynthesis>div,.memorySynthesis>aside{border:1px solid #ffffff19;border-radius:20px;padding:18px;background:#00000021}.memorySynthesis p,.memorySynthesis li{color:#aebccc;line-height:1.55}.memoryStrip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:12px}.memoryStrip article{display:grid;gap:4px;border-top:1px solid #ffffff1b;padding-top:9px}.memoryStrip span{font-size:9px;color:#8193a8;text-transform:uppercase}.memoryStrip b{color:#f0cb70}.memoryStrip small{color:#91a3b8;overflow-wrap:anywhere}.memorySynthesis aside ul{padding-left:18px}
.evidenceStack{display:grid;gap:10px}.evidenceStack>details{border:1px solid #ffffff18;border-radius:18px;padding:15px;background:#0000001d}.evidenceStack>details>summary{cursor:pointer;color:#e2c56b;font-weight:800;letter-spacing:.03em}.moduleDetails,.memoryTable,.historyGrid,.proofSources{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.moduleDetails article,.memoryTable article,.historyGrid article,.proofSources article{min-width:0;border:1px solid #ffffff15;border-radius:14px;padding:13px;background:#07101a}.moduleDetails header,.memoryTable article>div{display:flex;justify-content:space-between;gap:8px}.moduleDetails header span,.moduleDetails header em{font-size:9px;color:#8193a8}.moduleDetails p,.memoryTable p,.historyGrid p,.proofSources span{color:#aebccc;line-height:1.5}.detailColumns{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.memoryTable code,.historyGrid code,.proofSources code,.hashList code{display:block;white-space:normal;overflow-wrap:anywhere;color:#8193a8;font-size:10px}.methodNote{border-left:3px solid #f0cb70;padding-left:12px}.proofSources article{display:grid;gap:6px}.hashList{display:grid;gap:6px;margin-top:12px}.closingBoundary{margin-top:16px;border-top:1px solid #ffffff1b;padding-top:16px}.closingBoundary p{color:#8798aa;line-height:1.55}
.closingField{height:calc(clamp(128px,12vh,168px) + env(safe-area-inset-bottom));display:grid;place-items:start center;padding-top:48px}.closingField span{display:block;width:min(420px,61.803%);height:1px;background:linear-gradient(90deg,transparent,#f0cb7055,transparent)}
@media(max-width:1080px){.metricGrid{grid-template-columns:repeat(3,minmax(0,1fr))}.executiveGrid{grid-template-columns:1fr 1fr}.phiComposition,.memorySynthesis{grid-template-columns:1fr}.primaryField{min-height:330px}.supportField{grid-template-columns:repeat(3,minmax(0,1fr))}.supportField .moduleNode:last-child{grid-column:auto}.memoryStrip{grid-template-columns:1fr 1fr}}
@media(max-width:800px){main{padding-inline:12px}.questionPanel>header,.sectionHeading,.executiveRead>header{display:grid}.observation,.sectionHeading>p{text-align:left;justify-items:start}form{grid-template-columns:1fr}.readingQuestion{grid-template-columns:1fr}.readingQuestion>div:last-child{justify-items:start;text-align:left}.metricGrid,.executiveGrid,.memoryStrip,.moduleDetails,.memoryTable,.historyGrid,.proofSources,.detailColumns{grid-template-columns:1fr 1fr}.primaryField{grid-template-columns:1fr;min-height:auto}.btcCore{width:min(210px,65vw);justify-self:center}.supportField{grid-template-columns:1fr}.phiCaption{text-align:left}}
@media(max-width:520px){.metricGrid,.executiveGrid,.memoryStrip,.moduleDetails,.memoryTable,.historyGrid,.proofSources,.detailColumns{grid-template-columns:1fr}.reading{padding:16px 12px}.state{white-space:normal}.closingField{height:calc(128px + env(safe-area-inset-bottom))}}
`}</style></>}
