import { useEffect,useState } from "react";
import { useRouter } from "next/router";
import { resolvePublicLocale,switchPublicLocale,withPublicLocale } from "../lib/public-locale-transport";
const REQUEST_LOCALE_ROUTES=new Set(["/","/start","/frey","/reading","/cosmographer","/investors","/map","/faq","/services","/dao","/orion","/signal","/archive","/chronicle","/cosmography","/access","/support","/github","/guide/frey","/crypto-astro/btc","/crypto-astro/btc/live","/crypto-astro/btc/clean-chat"]);
function browserRoute(){if(typeof window==="undefined")return null;return `${window.location.pathname}${window.location.search}${window.location.hash}`;}
export default function BhriguPhiHeader(){
 const router=useRouter(); const stable=String(router.pathname||"/"); const [client,setClient]=useState(null);
 useEffect(()=>{const sync=()=>setClient(browserRoute());sync();window.addEventListener("popstate",sync);window.addEventListener("hashchange",sync);return()=>{window.removeEventListener("popstate",sync);window.removeEventListener("hashchange",sync);};},[router.asPath]);
 const active=client||stable; const path=active.split("?")[0].split("#")[0]; const raw=Array.isArray(router.query?.lang)?router.query.lang[0]:router.query?.lang;
 const requestLocale=REQUEST_LOCALE_ROUTES.has(stable)?resolvePublicLocale("",raw):"en"; const locale=client?resolvePublicLocale(client):requestLocale; const ru=locale==="ru"; const other=ru?"en":"ru";
 const home=path==="/"; const btc=path.startsWith("/crypto-astro/btc"); const homeHref=withPublicLocale("/",locale); const freyHref=withPublicLocale("/frey",locale); const orionHref=withPublicLocale("/orion",locale); const btcHref=withPublicLocale("/crypto-astro/btc",locale); const switchHref=switchPublicLocale(active,other);
 const onSwitch=(e)=>{const current=browserRoute();if(!current)return;e.preventDefault();window.location.assign(switchPublicLocale(current,other));};
 return <header className={`bh-header${home?" bh-header-home":""}${btc?" bh-header-btc":""}`}><div className="bh-shell"><a className="bh-brand" href={homeHref} aria-label={ru?"Главная BHRIGU":"BHRIGU home"}>BHRIGU</a><nav className="bh-ctas" aria-label={ru?"Основная навигация":"Primary navigation"}>{btc&&<a className="bh-btc-route" href={btcHref}>BTC Field</a>}{!home&&!btc&&<a className="bh-btn bh-btn-primary" href={freyHref}>{ru?"Открыть Frey":"Open Frey"}</a>}{!home&&!btc&&<a className="bh-btn" href={orionHref}>ORION</a>}<a className="bh-language" href={switchHref} onClick={onSwitch} aria-label={ru?"Открыть страницу на английском":"View this page in Russian"}>{ru?"EN":"RU"}</a></nav></div><style jsx>{`
 .bh-header{position:sticky;top:0;z-index:60;width:100%;border-bottom:1px solid rgba(255,255,255,.09);background:rgba(6,7,10,.9);backdrop-filter:blur(12px)}.bh-shell{width:100%;max-width:1180px;margin:0 auto;padding:14px 24px;display:flex;align-items:center;justify-content:space-between;gap:20px}.bh-brand{color:#dec27d!important;text-decoration:none;font-size:12px;font-weight:700;letter-spacing:.31em}.bh-ctas{display:flex;gap:10px;align-items:center}.bh-btn,.bh-language,.bh-btc-route{display:inline-flex;min-height:38px;align-items:center;justify-content:center;padding:0 14px;border:1px solid rgba(255,255,255,.13);border-radius:999px;color:rgba(255,255,255,.76)!important;text-decoration:none!important;font-size:10px;font-weight:650;letter-spacing:.1em;text-transform:uppercase}.bh-btn-primary{background:rgba(255,255,255,.92);color:#0a0b0d!important}.bh-btc-route{border-color:rgba(222,194,125,.38);color:#dec27d!important}.bh-language{min-width:40px;padding:0 10px}@media(max-width:620px){.bh-shell{padding:12px 18px}.bh-btn,.bh-btc-route{padding:0 10px;font-size:9px}}
 `}</style></header>;
}
