export const BTC_PRODUCT_REBALANCE_CSS = String.raw`
:root{
  --f:#05070c;--s:#09111d;--e:#0d1828;--t:#edf2f7;--t2:#b6c1cf;--m:#7f8fa2;
  --b:#d2a45f;--bh:#e7bf7e;--bl:rgba(106,168,255,.22);--bf:rgba(210,164,95,.075);
  --blue:#6aa8ff;--sup:#8f7cf4;--red:#d7867f;--g:#5d6978;
  --phi-major:61.803398875%;--phi-minor:38.196601125%;
}
html,body{background:radial-gradient(circle at 78% 12%,rgba(106,168,255,.07),transparent 31%),radial-gradient(circle at 16% 86%,rgba(143,124,244,.04),transparent 34%),var(--f)}
main{width:min(1360px,100%);padding-inline:clamp(18px,3.2vw,42px)}
main[data-btc-static-proof="true"],.heroProductEntry,.questionPanel{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.heroProductEntry{display:grid;grid-template-columns:minmax(0,.94fr) minmax(430px,1.06fr);gap:clamp(34px,4.8vw,72px);align-items:center;min-height:min(610px,calc(100svh - 96px));padding:clamp(30px,4vw,50px) 0;border-bottom:1px solid var(--bl)}
.heroProductCopy{align-self:center;max-width:39rem}.heroProductIdentity{display:grid;gap:7px;margin:0}.heroProductIdentity>span{color:var(--b);font-size:clamp(11px,.82vw,13px);font-weight:750;letter-spacing:.12em;text-transform:uppercase}.heroProductIdentity>small{color:var(--blue);font-size:clamp(9px,.68vw,11px);font-weight:750;letter-spacing:.13em;text-transform:uppercase}
.heroProductCopy h1{margin:.32em 0 .22em;font-size:clamp(50px,5.7vw,78px);line-height:.94;letter-spacing:-.062em;text-wrap:balance}
.heroProductCopy>p:last-child{max-width:36rem;color:var(--t2);font-size:clamp(17px,1.55vw,20px);line-height:1.62}
.heroQuestionCard{position:relative;isolation:isolate;overflow:hidden;min-height:clamp(360px,44svh,440px);display:grid;align-content:center;gap:16px;padding:clamp(26px,3.2vw,42px);border:1px solid rgba(106,168,255,.32);border-radius:26px 38px;background:radial-gradient(circle at 20% 18%,rgba(106,168,255,.08),transparent 28%),linear-gradient(145deg,rgba(11,23,40,.97),rgba(5,10,18,.99));box-shadow:0 26px 76px rgba(0,0,0,.32),inset 0 1px 0 rgba(255,255,255,.035)}
.heroQuestionCard:before{display:none}.heroQuestionHeader{position:relative;display:flex;gap:15px;align-items:flex-start}.heroQuestionHeader .eyebrow{color:var(--blue);font-size:11px;letter-spacing:.11em}.heroQuestionHeader h2{margin:5px 0 0;font-size:clamp(29px,3vw,42px);line-height:1.04;letter-spacing:-.038em;text-wrap:balance}
.heroQuestionGlyph{width:48px;height:48px;border-color:rgba(106,168,255,.58)}.heroQuestionGlyph b{color:var(--bh)}
.heroQuestionLead{position:relative;max-width:40rem;margin:0;color:var(--t2);font-size:clamp(15px,1.35vw,17px);line-height:1.58}
.heroValuePath{position:relative;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0;padding:12px 0;border-top:1px solid rgba(106,168,255,.16);border-bottom:1px solid rgba(106,168,255,.12)}
.heroValuePath span{min-width:0;padding:0 9px;border:0;background:transparent;color:var(--m);font-size:10px;font-weight:700;line-height:1.35;letter-spacing:.055em;text-align:center;text-transform:uppercase}.heroValuePath span+span{border-left:1px solid rgba(106,168,255,.13)}
.heroDialogueCta{position:relative;display:flex;align-items:center;justify-content:space-between;gap:18px;width:100%;padding:17px 21px;border:1px solid rgba(106,168,255,.52);border-radius:999px;background:linear-gradient(110deg,rgba(106,168,255,.16),rgba(143,124,244,.075));color:var(--t);text-decoration:none;font-weight:750;box-shadow:0 14px 34px rgba(20,53,96,.16)}
.heroDialogueCta:hover{border-color:rgba(106,168,255,.72);background:linear-gradient(110deg,rgba(106,168,255,.24),rgba(143,124,244,.12))}.heroDialogueCta span{color:var(--bh);font-size:20px}
.heroDialogueGateway{min-height:clamp(350px,43svh,430px)}
.heroQuestionBoundary{position:relative;display:grid;grid-template-columns:auto auto;justify-content:start;gap:3px 14px;margin:0;color:var(--m);line-height:1.45}.heroQuestionBoundary>span{font-size:10px;letter-spacing:.025em}.heroQuestionBoundary>span+span{color:#8da5c5}.heroQuestionBoundary>small{grid-column:1/-1;color:#67778c;font-size:8.5px;letter-spacing:.018em}
.btcSystemCompression{position:relative;overflow:hidden;margin:0;padding:clamp(28px,4.6vw,54px) 0 clamp(30px,4.8vw,58px);border-bottom:1px solid var(--bl);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.btcSystemCompression:before{content:"";position:absolute;inset:0 0 auto 61.803398875%;height:1px;background:linear-gradient(90deg,var(--blue),transparent);opacity:.42}.btcCompressionHead{display:grid;grid-template-columns:minmax(0,.75fr) minmax(0,1.25fr);gap:10px clamp(24px,4vw,56px);align-items:end}.btcCompressionHead .eyebrow{grid-column:1/-1;margin:0;color:var(--blue);font-size:9px;letter-spacing:.16em;text-transform:uppercase}.btcCompressionHead h2{margin:0;font-size:clamp(31px,4vw,48px);line-height:1;letter-spacing:-.045em}.btcCompressionHead>p:last-child{max-width:42rem;margin:0;color:var(--t2);font-size:14px;line-height:1.55}
.btcLayerRail{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:26px}.btcLayerRail article{position:relative;min-width:0;min-height:142px;display:grid;align-content:start;gap:6px;padding:14px 13px;border:1px solid rgba(106,168,255,.16);background:linear-gradient(155deg,rgba(10,21,36,.76),rgba(5,10,18,.88))}.btcLayerRail article+article:before{content:"→";position:absolute;left:-8px;top:50%;z-index:2;transform:translate(-50%,-50%);color:rgba(106,168,255,.55);font-size:11px}.btcLayerRail article:nth-child(2){border-color:rgba(210,164,95,.22)}.btcLayerRail article:nth-child(3){border-color:rgba(143,124,244,.26)}.btcLayerRail article:nth-child(4){border-color:rgba(143,124,244,.22)}.btcLayerRail article:nth-child(5){border-color:rgba(106,168,255,.3)}.btcLayerRail article>span{color:var(--blue);font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace;font-size:8px}.btcLayerRail article>small{color:var(--m);font-size:7.5px;font-weight:750;letter-spacing:.09em;text-transform:uppercase}.btcLayerRail article>strong{color:var(--t);font-size:13px;letter-spacing:.035em}.btcLayerRail article>p{margin:5px 0 0;color:var(--t2);font-size:11px;line-height:1.45}
.btcEvidenceFlow{margin-top:18px;padding:16px;border:1px solid rgba(210,164,95,.18);background:linear-gradient(90deg,rgba(210,164,95,.035),rgba(106,168,255,.025))}.btcFlowLabel{margin:0 0 12px;color:var(--b);font-size:8px;font-weight:750;letter-spacing:.15em;text-transform:uppercase}.btcFlowRail{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:0}.btcFlowRail article{position:relative;min-width:0;display:grid;gap:4px;padding:8px 12px}.btcFlowRail article+article{border-left:1px solid rgba(106,168,255,.14)}.btcFlowRail article+article:before{content:"→";position:absolute;left:0;top:50%;transform:translate(-50%,-50%);padding:2px;background:var(--f);color:rgba(106,168,255,.55);font-size:9px}.btcFlowRail span{color:rgba(106,168,255,.58);font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace;font-size:7px}.btcFlowRail strong{color:var(--t);font-size:10px;letter-spacing:.045em}.btcFlowRail small{color:var(--m);font-size:8.5px;line-height:1.35}
.snapshotTruthStrip{display:flex;flex-wrap:wrap;align-items:center;gap:8px 22px;margin:0;padding:17px 0 20px;border-bottom:1px solid var(--bl);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.snapshotTruthStrip>strong{display:flex;align-items:center;gap:10px;margin-right:auto;font-size:14px;line-height:1.35}.snapshotTruthStrip>strong:before{content:"";width:8px;height:8px;border-radius:50%;background:var(--m);box-shadow:0 0 0 5px rgba(127,143,162,.08)}.snapshotTruthStrip[data-freshness-state="FRESH"]>strong:before{background:var(--blue);box-shadow:0 0 0 5px rgba(106,168,255,.1)}.snapshotTruthStrip[data-freshness-state="STALE_LIMITED"]>strong:before{background:var(--b);box-shadow:0 0 0 5px rgba(210,164,95,.1)}.snapshotTruthStrip[data-freshness-state="UNAVAILABLE"]>strong:before{background:var(--red);box-shadow:0 0 0 5px rgba(215,134,127,.1)}.snapshotTruthStrip>p{margin:0;color:var(--t2);font-size:13px;line-height:1.45}.snapshotTruthStrip>p:has(code){display:none}.snapshotTruthStrip>p:not(:has(code)){justify-self:auto}.snapshotTruthStrip>p:not(:has(code))+p:not(:has(code)):before{content:none}
.productOutcomeHeader{display:grid;gap:10px;max-width:760px;padding:clamp(40px,5.6vw,70px) 0 22px}.productOutcomeHeader h2{margin:0;font-size:clamp(35px,5vw,60px);line-height:1;letter-spacing:-.045em;text-wrap:balance}.productOutcomeHeader>p:last-child{margin:0;color:var(--t2);font-size:17px;line-height:1.6}
.productOutcomeGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:clamp(34px,5vw,64px);padding-top:clamp(28px,4vw,48px);border-top:1px solid rgba(106,168,255,.2);margin-bottom:clamp(46px,6vw,78px)}
.productOutcomeGrid article{min-height:190px;padding:20px;border:1px solid rgba(106,168,255,.18);border-radius:16px;background:linear-gradient(145deg,rgba(9,19,33,.74),rgba(5,10,18,.78))}.productOutcomeGrid article:nth-child(3){border-color:rgba(143,124,244,.3)}.productOutcomeGrid article:nth-child(4){border-color:rgba(210,164,95,.3)}
.productOutcomeGrid span{color:var(--blue);font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace;font-size:11px}.productOutcomeGrid h3{margin:24px 0 10px;color:var(--t);font-size:19px;line-height:1.2}.productOutcomeGrid p{margin:0;color:var(--t2);font-size:14px;line-height:1.55}
.fieldNav{background:rgba(5,7,12,.92);border-color:var(--bl)}
.questionPanel{border-color:var(--bl)}
.staticProofHeader{display:grid;align-content:start;gap:18px;padding:clamp(30px,4vw,54px)}.staticProofHeader>p{margin:0;color:var(--t2);line-height:1.65}.staticExampleRoutes{border-left:1px solid var(--bl);padding-top:clamp(28px,3vw,40px)}
.questionPanel,.readingZone{border-color:var(--bl)}
.questionMembrane,.readingHeader,.executiveField,.phiPlane{grid-template-columns:minmax(0,61.803398875fr) minmax(280px,38.196601125fr)}
.questionMembrane.proofRouteMembrane{grid-template-columns:minmax(0,38.196601125fr) minmax(0,61.803398875fr);border-top:1px solid var(--bl)}
.exampleRoutes,.executiveContext,.supportBand{border-color:var(--bl)}
.phiPlane>.supportBand{grid-template-columns:minmax(0,1fr)}
.phiPlane>.supportBand>.supportModule,.phiPlane>.supportBand>.supportModule:last-child{grid-column:auto;min-width:0;border-right:0}
.phiPlane>.supportBand>.supportModule h3,.phiPlane>.supportBand>.supportModule strong,.phiPlane>.supportBand>.supportModule p{max-width:100%;overflow-wrap:break-word;word-break:normal}

textarea,input{border-color:rgba(106,168,255,.2);background:rgba(9,17,29,.88)}textarea:focus,input:focus{border-color:rgba(106,168,255,.66);box-shadow:0 0 0 3px rgba(106,168,255,.08);outline:0}button{border-color:rgba(210,164,95,.58)}
.eyebrow{color:var(--b)}.fieldAnchorGlyph{border-color:rgba(106,168,255,.48);background:radial-gradient(circle,rgba(106,168,255,.1),transparent 68%)}.fieldAnchorGlyph:after{border-color:rgba(210,164,95,.16)}.fieldAnchorGlyph b{color:var(--bh)}

.polymarketExpectationZone{position:relative;overflow:hidden;margin-top:clamp(34px,4vw,54px);padding:clamp(28px,3.6vw,44px) 0;border-top:1px solid rgba(106,168,255,.24);border-bottom:1px solid rgba(106,168,255,.16);background:linear-gradient(90deg,rgba(106,168,255,.035),transparent 64%)}
.polymarketExpectationZone:before{content:"Φ";position:absolute;right:clamp(8px,4vw,48px);top:12px;color:rgba(210,164,95,.055);font-size:clamp(92px,12vw,170px);font-weight:300;line-height:1;pointer-events:none}.polymarketExpectationHead{position:relative;z-index:1}.polymarketExpectationHead>p{max-width:38rem;color:var(--t2);line-height:1.62}.polymarketExpectationArc{position:relative;z-index:1;display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr) auto minmax(0,1fr);gap:16px;align-items:stretch;margin-top:28px}.polymarketExpectationArc article{min-width:0;padding:20px;border:1px solid rgba(106,168,255,.18);border-radius:14px 24px;background:rgba(9,17,29,.52)}.polymarketExpectationArc article:nth-of-type(3){border-color:rgba(210,164,95,.24)}.polymarketExpectationArc article>span{color:var(--blue);font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace;font-size:9px}.polymarketExpectationArc strong{display:block;margin-top:17px;color:var(--t);font-size:17px;line-height:1.2}.polymarketExpectationArc p{margin:8px 0 0;color:var(--t2);font-size:13px;line-height:1.55}.polymarketExpectationArc>i{align-self:center;color:rgba(106,168,255,.5);font-style:normal}.polymarketExpectationBoundary{position:relative;z-index:1;display:flex;flex-wrap:wrap;gap:8px 18px;margin-top:20px;padding-top:15px;border-top:1px solid rgba(106,168,255,.12);color:var(--m);font-size:9px;letter-spacing:.065em;text-transform:uppercase}.polymarketExpectationBoundary span+span:before{content:"·";margin-right:18px;color:var(--blue)}.polymarketExpectationCta{position:relative;z-index:1;display:inline-flex;gap:12px;margin-top:18px;color:var(--blue)!important;font-size:12px;font-weight:700;text-decoration:none}.polymarketExpectationCta:hover{color:var(--bh)!important}
.btcAuthorityFooter{margin-top:clamp(54px,7vw,92px);padding:clamp(34px,4.5vw,54px) 0 22px;border-top:1px solid rgba(106,168,255,.24);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.btcAuthorityFooterIntro{display:grid;grid-template-columns:minmax(0,38.196601125fr) minmax(0,61.803398875fr);gap:clamp(28px,4vw,56px);align-items:end;padding-bottom:30px;border-bottom:1px solid rgba(106,168,255,.14)}
.btcAuthorityFooterIdentity{display:grid;gap:8px}.btcAuthorityFooterIdentity strong{font-size:13px;letter-spacing:.13em;text-transform:uppercase}.btcAuthorityFooterIdentity p,.btcAuthorityFooterStatement{margin:0;color:var(--t2);line-height:1.6}.btcAuthorityFooterIdentity p{max-width:28rem;font-size:14px}.btcAuthorityFooterStatement{max-width:48rem;font-size:clamp(17px,1.6vw,20px)}
.btcAuthorityFooterNav{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:clamp(18px,3vw,38px);padding:30px 0}.btcAuthorityFooterNav section{min-width:0}.btcAuthorityFooterNav h3{margin:0 0 12px;color:var(--m);font-size:9px;letter-spacing:.13em;text-transform:uppercase}.btcAuthorityFooterNav a,.btcAuthorityFooterNav .btcBoundaryStatement{display:block;width:max-content;max-width:100%;padding:5px 0;color:var(--t2);font-size:12px;line-height:1.4;text-decoration:none}.btcAuthorityFooterNav a:hover{color:var(--t)}.btcAuthorityFooterNav .btcBoundaryStatement{cursor:default}
.btcFooterTrustStrip{display:flex;flex-wrap:wrap;gap:8px 18px;align-items:center;padding:14px 0;border-top:1px solid rgba(106,168,255,.14);border-bottom:1px solid rgba(106,168,255,.14);color:var(--m);font-size:10px;letter-spacing:.055em;text-transform:uppercase}.btcFooterTrustStrip strong{color:var(--t2)}.btcFooterTrustStrip time{font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace;text-transform:none}.btcFooterTrustStrip span+span:before,.btcFooterTrustStrip time:before{content:"·";margin-right:18px;color:var(--blue)}
.btcFooterBottom{display:flex;justify-content:space-between;gap:18px;padding-top:18px;color:#68788c;font-size:9px;letter-spacing:.11em;text-transform:uppercase}.btcFooterBottom strong{color:#8798ad;font-weight:700}

main[data-btc-static-proof="true"] :where(.heroQuestionHeader .eyebrow,.heroValuePath span,.heroQuestionBoundary>span,.heroQuestionBoundary>small,.btcCompressionHead .eyebrow,.btcLayerRail article>span,.btcLayerRail article>small,.btcLayerRail article>p,.btcFlowLabel,.btcFlowRail span,.btcFlowRail strong,.btcFlowRail small,.productOutcomeGrid span,.polymarketExpectationArc article>span,.polymarketExpectationBoundary,.polymarketExpectationCta,.btcAuthorityFooterNav h3,.btcFooterTrustStrip,.btcFooterBottom){font-size:12px}
main[data-btc-static-proof="true"] :where(.heroQuestionBoundary>span+span,.btcLayerRail article>span,.btcFlowRail span,.btcFooterTrustStrip){color:var(--blue)}
main[data-btc-static-proof="true"] :where(.heroQuestionBoundary>small,.btcFooterBottom){color:var(--t2)}

.metricRibbon,.phiPlane,.memoryAxis,.evidenceStack{border-color:var(--bl)}.btcAxis:before{background:linear-gradient(90deg,var(--blue),rgba(210,164,95,.42),rgba(237,242,247,.1))}.closingField span{background:linear-gradient(90deg,transparent,rgba(106,168,255,.32),rgba(210,164,95,.2),transparent)}
@media(max-width:1080px){.btcCompressionHead{grid-template-columns:1fr}.btcLayerRail{grid-template-columns:repeat(3,minmax(0,1fr))}.btcLayerRail article+article:before{display:none}.btcFlowRail{grid-template-columns:repeat(5,minmax(0,1fr))}}
@media(max-width:680px){.btcSystemCompression{padding:24px 0 28px}.btcCompressionHead{gap:8px}.btcCompressionHead h2{font-size:32px}.btcCompressionHead>p:last-child{font-size:13px;line-height:1.45}.btcLayerRail{grid-template-columns:1fr;gap:6px;margin-top:20px}.btcLayerRail article{min-height:0;grid-template-columns:28px minmax(0,.65fr) minmax(0,1.35fr);gap:5px 8px;align-items:baseline;padding:11px 12px}.btcLayerRail article>span{grid-row:1/3}.btcLayerRail article>small{grid-column:2}.btcLayerRail article>strong{grid-column:3}.btcLayerRail article>p{grid-column:2/4;margin:1px 0 0;font-size:10px}.btcEvidenceFlow{margin-top:12px;padding:12px}.btcFlowRail{grid-template-columns:1fr}.btcFlowRail article{grid-template-columns:24px minmax(0,.7fr) minmax(0,1.3fr);gap:5px 8px;align-items:baseline;padding:8px 4px}.btcFlowRail article+article{border-left:0;border-top:1px solid rgba(106,168,255,.1)}.btcFlowRail article+article:before{content:"↓";left:12px;top:0}.btcFlowRail span{grid-row:1}.btcFlowRail strong{grid-column:2}.btcFlowRail small{grid-column:3}.btcFlowLabel{margin-bottom:8px}}
@media(max-width:1080px){.heroProductEntry{grid-template-columns:1fr;min-height:auto;padding-top:42px}.heroProductCopy{max-width:50rem}.heroQuestionCard{min-height:0}.productOutcomeGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.snapshotTruthStrip{align-items:flex-start}.snapshotTruthStrip>strong{width:100%;margin-right:0}.readingHeader,.executiveField,.phiPlane{grid-template-columns:1fr}.executiveContext,.supportBand{border-left:0;border-top:1px solid var(--bl);padding-left:0}.phiPlane{overflow:visible}}
@media(max-width:900px){.questionMembrane.proofRouteMembrane{grid-template-columns:1fr}.staticExampleRoutes{border-left:0;border-top:1px solid var(--bl)}}
@media(max-width:680px){
.polymarketExpectationArc{grid-template-columns:1fr;gap:9px}.polymarketExpectationArc>i{display:none}.polymarketExpectationArc article{padding:16px}.polymarketExpectationBoundary{display:grid;gap:5px}.polymarketExpectationBoundary span+span:before{content:none}
.readingHeader,.executiveField,.phiPlane{grid-template-columns:1fr;gap:22px}.readingHeader>div,.readingHeader>dl,.executivePrimary,.executiveContext,.primaryField,.supportBand{min-width:0;width:100%}.readingHeader h2{max-width:100%;font-size:clamp(25px,7.6vw,32px);line-height:1.1;letter-spacing:-.03em;text-wrap:pretty;overflow-wrap:normal}.readingHeader dl{margin-top:2px}.executiveField{gap:20px}.executivePrimary dl{grid-template-columns:1fr;gap:12px}.executivePrimary h3{font-size:clamp(34px,10vw,44px);line-height:.98}.executiveLead{font-size:16px;line-height:1.58}.executiveContext{padding:18px 0 0}.executivePrimary dd,.executiveContext dd{line-height:1.58}.phiPlane{display:grid;grid-template-columns:1fr;gap:0;overflow:visible}.phiRouteGlyph{display:none}.phiPlane>.primaryField,.phiPlane>.supportBand{display:contents}.phiPlane .btcAxis{order:0;min-height:132px;padding:22px 0;border-bottom:1px solid rgba(238,232,220,.1)}.phiPlane .btcAxis>span{font-size:clamp(54px,16vw,72px)}.phiPlane .module-market_structure{order:1}.phiPlane .module-liquidity_membrane{order:2}.phiPlane .module-change_event_memory{order:3}.phiPlane .module-temporal_context{order:4}.phiPlane .module-cosmographer_review{order:5}.phiPlane .phiModule{width:100%;min-width:0;padding:18px 0;border-right:0;border-bottom:1px solid rgba(238,232,220,.1)}.phiPlane .primaryModule h3,.phiPlane .supportModule h3{font-size:clamp(21px,6vw,28px);line-height:1.08}.phiPlane .primaryModule p,.phiPlane .supportModule p{margin-bottom:0;line-height:1.58}.memoryTableWrap{overflow:visible}.memoryAxis table{min-width:0!important;margin-top:14px}.memoryAxis thead{display:none}.memoryAxis tbody{display:grid;gap:10px}.memoryAxis tbody tr{display:grid;width:100%;padding:13px 14px;border:1px solid rgba(238,232,220,.1);border-radius:12px;background:rgba(9,17,29,.36)}.memoryAxis tbody th,.memoryAxis tbody td{display:grid;width:100%;min-width:0;border-bottom:0;padding:5px 0}.memoryAxis tbody th{padding-bottom:9px;color:var(--t);font-size:12px}.memoryAxis tbody td{grid-template-columns:minmax(82px,38.196601125fr) minmax(0,61.803398875fr);gap:10px;color:var(--t2);font-size:11px}.memoryAxis tbody td:before{content:attr(data-mobile-label);color:var(--m);font-size:8px;letter-spacing:.09em;text-transform:uppercase}.memoryScale{gap:9px}.memoryScale span{font-size:8px}.btcAuthorityFooter{margin-top:48px}.btcAuthorityFooterNav{padding:24px 0}
main{padding-inline:16px}.heroProductEntry{gap:13px;padding:19px 0 23px}.heroProductIdentity{gap:5px}.heroProductIdentity>span{font-size:9.5px;letter-spacing:.085em}.heroProductIdentity>small{font-size:8.5px;letter-spacing:.11em}.heroProductCopy h1{margin:.22em 0 .1em;font-size:clamp(40px,11.5vw,52px);line-height:.95}.heroProductCopy>p:last-child{display:block;max-width:32rem;font-size:14px;line-height:1.43}.heroQuestionCard{min-height:0;gap:9px;padding:16px 15px;border-radius:20px 28px}.heroQuestionHeader{order:0;gap:10px}.heroQuestionHeader .eyebrow{font-size:9px;letter-spacing:.09em}.heroQuestionHeader h2{margin-top:3px;font-size:clamp(25px,7.4vw,30px);line-height:1}.heroQuestionGlyph{width:38px;height:38px}.heroDialogueCta{order:1;padding:13px 16px;font-size:14px}.heroQuestionLead{order:2;font-size:13px;line-height:1.4}.heroValuePath{order:3;grid-template-columns:repeat(2,minmax(0,1fr));row-gap:7px;padding:8px 0}.heroValuePath span{padding:0 5px;font-size:8.5px}.heroValuePath span:nth-child(3){border-left:0}.heroQuestionBoundary{order:4;grid-template-columns:1fr 1fr;gap:2px 10px}.heroQuestionBoundary>span{font-size:8.5px}.heroQuestionBoundary>small{grid-column:1/-1;font-size:7.5px}.snapshotTruthStrip{display:grid;grid-template-columns:1fr;gap:6px;padding:14px 0 17px}.snapshotTruthStrip>strong{width:auto}.snapshotTruthStrip>p{font-size:12px}.productOutcomeHeader{padding-top:38px}.productOutcomeHeader h2{font-size:36px}.productOutcomeGrid{grid-template-columns:1fr;gap:9px;margin-top:30px;padding-top:24px}.productOutcomeGrid article{min-height:0}.productOutcomeGrid h3{margin-top:16px}.proofRouteMembrane{display:block}.staticProofHeader{gap:14px;padding:26px 0}.staticProofHeader .questionTitleLockup{align-items:flex-start}.staticProofHeader h2{font-size:clamp(27px,8vw,32px);line-height:1.05}.staticProofHeader>p{font-size:14px;line-height:1.55}.staticExampleRoutes{margin:0;padding:26px 0 0}.staticExampleRoutes h3{font-size:23px;line-height:1.1}.exampleRouteList a{grid-template-columns:26px minmax(0,1fr) 18px;gap:8px;padding:15px 0}.exampleRouteList b,.exampleRouteList em{min-width:0;overflow-wrap:anywhere}.btcAuthorityFooterIntro{grid-template-columns:1fr;gap:18px}.btcAuthorityFooterNav{grid-template-columns:repeat(2,minmax(0,1fr));gap:22px 18px}.btcFooterTrustStrip{display:grid;grid-template-columns:1fr;gap:5px}.btcFooterTrustStrip span+span:before,.btcFooterTrustStrip time:before{content:none}.btcFooterBottom{display:grid;gap:7px}
}
`;
